# Generated by Django 3.0.3 on 2020-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=30)),
                ('gross_revenue', models.IntegerField()),
                ('contractual_adjustments', models.IntegerField()),
                ('other_deductions', models.IntegerField()),
                ('additions_to_revenue', models.IntegerField()),
                ('deductions', models.IntegerField()),
                ('net_revenue', models.IntegerField()),
                ('price_cost_ratio', models.IntegerField()),
            ],
        ),
    ]
