# Generated by Django 3.0.5 on 2020-04-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_auto_20200404_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='additions_to_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contractual_adjustments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='other_deductions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
